[package]
name = "scheme-compiler"
version = "0.1.0"
authors = ["Sankha Narayan Guria <sankha93@gmail.com>"]
edition = "2018"

[lib]
name = "compiler"
path = "src/lib.rs"

[dependencies]
glob = "*"
language = { path = "language" }
interpreter = { path = "interpreter" }
